routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[\App\Http\Controllers\websiteController::class,'news'])->name('news');
Route::get('/new-by-cat/{cat}',[\App\Http\Controllers\websiteController::class,'newsByCategory'])->name('get_news_by_cat');
Route::get('/test',[\App\Http\Controllers\Admin\Homecotroller::class,'welcome']);
Route::get('/about',[\App\Http\Controllers\websiteController::class,'about'])->name('website.about');


Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>'auth'],function (){
    Route::group(['prefix'=>'manage'],function(){
        Route::get('/',[\App\Http\Controllers\Admin\AdminController::class,'index'])->name('users');
        Route::get('/create',[\App\Http\Controllers\Admin\AdminController::class,'create'])->name('create.user');
        Route::get('/edit/{admin}',[\App\Http\Controllers\Admin\AdminController::class,'edit'])->name('edit.user');
        Route::post('/update/{admin}',[\App\Http\Controllers\Admin\AdminController::class,'update'])->name('update.user');
        Route::post('/store',[\App\Http\Controllers\Admin\AdminController::class,'store'])->name('user.store');
        Route::post('/destroy/{admin}',[\App\Http\Controllers\Admin\AdminController::class,'destroy'])->name('user.destroy');
    });
    Route::group(['prefix'=>'category'],function(){
        Route::get('/',[\App\Http\Controllers\Admin\CategoryController::class,'index'])->name('category');
        Route::get('/create',[\App\Http\Controllers\Admin\CategoryController::class,'create'])->name('category.create');
        Route::post('/store',[\App\Http\Controllers\Admin\CategoryController::class,'store'])->name('category.store');
        Route::get('/edit/{category}',[\App\Http\Controllers\Admin\CategoryController::class,'edit'])->name('category.edit');
        Route::post('/update/{category}',[\App\Http\Controllers\Admin\CategoryController::class,'update'])->name('category.update');
        Route::post('/destroy/{category}',[\App\Http\Controllers\Admin\categoryController::class,'destroy'])->name('category.destroy');

    });
    Route::group(['prefix'=>'news'],function (){
        Route::get('/',[\App\Http\Controllers\Admin\NewsController::class,'index'])->name('news');

        Route::get('/create',[\App\Http\Controllers\Admin\NewsController::class,'create'])->name('news.create');
        Route::post('/store',[\App\Http\Controllers\Admin\NewsController::class,'store'])->name('news.store');
        Route::get('/edit/{news}',[\App\Http\Controllers\Admin\NewsController::class,'edit'])->name('news.edit');
        Route::post('/update/{news}',[\App\Http\Controllers\Admin\NewsController::class,'update'])->name('news.update');
        Route::post('/destroy/{news}',[\App\Http\Controllers\Admin\NewsController::class,'destroy'])->name('news.destroy');
    });
    Route::get('/home',[\App\Http\Controllers\Admin\Homecotroller::class,'admin'])->name('admin');
});

Auth::routes(['register'=>false]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('admin');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $fillable = [
        'name'
    ];
    public function news(){
        return $this->hasMany(News::class,'cat_id');
    }
}

app/Http/Controllers/Admin/categoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class categoryController extends Controller
{
public function index(){
        $category=Category::all();
    $data=[
        'category'=>$category
    ];
    return view('admin.category.index',$data);
}

    public function create(Request $request){

        return view('admin.category.addCategory');

    }
    public function store(Request $request){
        $category = new Category();
        $category->name=$request->name;
        $category->save();
        return redirect()->to(route('admin.category'))->with('success','تم إضافة المنتج بنجاح');
    }
    public function edit(Request $request,Category $category){

        return view('admin.category.editCategory',compact('category'));

    }
    public function update(Request $request,Category $category){
        $request->validate([
            'name'=>'required',
        ]);
        $category->name=$request->name;
        $category->save();
        return redirect()->to(route('admin.category'))->with('success','تم تحديث اسم بنجاح');
    }
    public function destroy(Request $request,$category){
        $category=Category::find($category);
        if ($category){
            $category->delete();
        }
        return redirect()->to(route('admin.category'))->with('success','تم حذف المنتج بنجاح');

    }
}

resources/views/admin/category/addCategory.blade.php
@extends('admin.layout.app')
@section('content')
    @push('css')
    @endpush
    @push('js')
    @endpush
    <div class="card card-custom">
        <div class="card-header">
            <h3 class="card-title">
                Add Category
            </h3>
        </div>
        <!--begin::Form-->
        <form class="form" action="{{route('admin.category.store')}}" method="post">
            @csrf
            <div class="card-body">

                <div class="form-group">
                    <label>Name Of Category</label>
                    <input type="text" name="name" class="form-control form-control-lg"  placeholder="category name"/>
                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-success mr-2">Save</button>
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                </div>
                </div>
        </form>
        <!--end::Form-->
    </div>@endsection

resources/views/admin/category/editCategory.blade.php
@extends('admin.layout.app')
@section('content')
    @push('css')
    @endpush
    @push('js')
    @endpush
    <div class="card card-custom">
        <div class="card-header">
            <h3 class="card-title">
                Add Category
            </h3>
        </div>
        <!--begin::Form-->
        <form class="form" action="{{route('admin.category.update',['category'=>$category])}}" method="post">
            @csrf
            <div class="card-body">

                <div class="form-group">
                    <label>Name Of Category</label>
                    <input type="text" name="name" class="form-control form-control-lg"  placeholder="category name" value="{{@$categoryx->name}}"/>
                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-success mr-2">Save</button>
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                </div>
            </div>
        </form>
        <!--end::Form-->
    </div>@endsection

resources/views/admin/category/index.blade.php
@extends('admin.layout.app')
@section('content')
    @push('css')
    @endpush
    <div class="card card-custom">
        <div class="card-header">
            <div class="card-title">
            <span class="card-icon">
                <i class="fa fa-user-cog text-primary"></i>
            </span>
                <h3 class="card-label">
                    Category Management
                </h3>
            </div>
            <div class="card-toolbar">
                <a href="{{route('admin.category.create')}}" class="btn btn-sm btn-light-primary font-weight-bold">
                    <i class="fa fa-plus"></i> ADD NEW CATEGORY
                </a>
            </div>
        </div>
        <div class="card-body">
            @if(session()->has('success'))

                <div class="alert alert-dismissible bg-success d-flex flex-column flex-sm-row p-5 mb-10">
                    <span class="svg-icon-2hx svg-icon-light me-4 mb-5 mb-sm-0"></span>
                    <div class="d-flex flex-column text-light pe-0 pr-sm-10">
                        <span>{{session()->get('success')}}</span>
                    </div>
                    <button type="button" class="position-absolute position-sm-relative m-2 m-sm-0 top-0 end-0 btn btn-icon ms-sm-auto" data-bs-dismiss="alert">
                        <span class="svg-icon svg-icon-2x svg-icon-light"></span>
                    </button>
                </div>
            @endif
            <div>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <td>#</td>
                        <td>Name</td>
                        <td>News Count</td>
                        <td>Created At</td>

                    </tr>
                    </thead>
                    <tbody>
                    @foreach($category as $key=>$cats)
                        <tr>
                            <td>{{ $key+1}}</td>
                            <td>{{$cats->name}}</td>
                            <td>{{$cats->news->count()}}</td>
                            <td>{{$cats->created_at}}</td>
                            <td>
                            <a href="{{route('admin.category.edit',['category'=>$cats])}}" class="btn btn-icon">
                                <i class="fa fa-user-edit"></i>
                            </a>





                                <form action="{{route('admin.category.destroy',['category'=>$cats->id])}}" method="post">

                                    @csrf
                                    <button type="submit" class="btn btn-icon red">
                                        <i class="fa fa-trash"></i>
                                    </button>




                                </form>


                            <td/>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="row text-center">
{{--                    {{$category->links()}}--}}
                </div>
            </div>
        </div>

    </div>
@endsection
{{--@push('js')--}}
{{--    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>--}}
{{--    <script type="text/javascript">--}}

{{--        $('.show_confirm').click (function(event) {--}}

{{--            var form = $(this).closest("form");--}}
{{--            var name = $(this).data ("name");--}}

{{--            event.preventDefault();--}}
{{--            swal ({--}}

{{--                title: "Are you sure you want to delete"+name+ '?',--}}
{{--                text: "If you delete this, it will be gone forever.",--}}
{{--                icon: "warning",--}}
{{--                buttons: true,--}}
{{--                dangerMode: true,--}}

{{--            })--}}

{{--                .then((willDelete) => {--}}

{{--                    if (willDelete) {--}}
{{--                        form.submit();--}}

{{--                    }--}}



{{--                });--}}

{{--        });--}}

{{--    </script>--}}
{{--@endpush--}}