routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[\App\Http\Controllers\websiteController::class,'news'])->name('news');
Route::get('/new-by-cat/{cat}',[\App\Http\Controllers\websiteController::class,'newsByCategory'])->name('get_news_by_cat');
Route::get('/test',[\App\Http\Controllers\Admin\Homecotroller::class,'welcome']);
Route::get('/about',[\App\Http\Controllers\websiteController::class,'about'])->name('website.about');


Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>'auth'],function (){
    Route::group(['prefix'=>'manage'],function(){
        Route::get('/',[\App\Http\Controllers\Admin\AdminController::class,'index'])->name('users');
        Route::get('/create',[\App\Http\Controllers\Admin\AdminController::class,'create'])->name('create.user');
        Route::get('/edit/{admin}',[\App\Http\Controllers\Admin\AdminController::class,'edit'])->name('edit.user');
        Route::post('/update/{admin}',[\App\Http\Controllers\Admin\AdminController::class,'update'])->name('update.user');
        Route::post('/store',[\App\Http\Controllers\Admin\AdminController::class,'store'])->name('user.store');
        Route::post('/destroy/{admin}',[\App\Http\Controllers\Admin\AdminController::class,'destroy'])->name('user.destroy');
    });
    Route::group(['prefix'=>'category'],function(){
        Route::get('/',[\App\Http\Controllers\Admin\CategoryController::class,'index'])->name('category');
        Route::get('/create',[\App\Http\Controllers\Admin\CategoryController::class,'create'])->name('category.create');
        Route::post('/store',[\App\Http\Controllers\Admin\CategoryController::class,'store'])->name('category.store');
        Route::get('/edit/{category}',[\App\Http\Controllers\Admin\CategoryController::class,'edit'])->name('category.edit');
        Route::post('/update/{category}',[\App\Http\Controllers\Admin\CategoryController::class,'update'])->name('category.update');
        Route::post('/destroy/{category}',[\App\Http\Controllers\Admin\categoryController::class,'destroy'])->name('category.destroy');

    });
    Route::group(['prefix'=>'news'],function (){
        Route::get('/',[\App\Http\Controllers\Admin\NewsController::class,'index'])->name('news');

        Route::get('/create',[\App\Http\Controllers\Admin\NewsController::class,'create'])->name('news.create');
        Route::post('/store',[\App\Http\Controllers\Admin\NewsController::class,'store'])->name('news.store');
        Route::get('/edit/{news}',[\App\Http\Controllers\Admin\NewsController::class,'edit'])->name('news.edit');
        Route::post('/update/{news}',[\App\Http\Controllers\Admin\NewsController::class,'update'])->name('news.update');
        Route::post('/destroy/{news}',[\App\Http\Controllers\Admin\NewsController::class,'destroy'])->name('news.destroy');
    });
    Route::get('/home',[\App\Http\Controllers\Admin\Homecotroller::class,'admin'])->name('admin');
});

Auth::routes(['register'=>false]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('admin');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


}

resources/views/admin/users/create.blade.php
@extends('admin.layout.app')
@section('content')
    @push('css')
    @endpush
    @push('js')
    @endpush
    <div class="card card-custom">
        <div class="card-header">
            <div class="card-title">
            <span class="card-icon">
                <i class="fa fa-user-plus text-primary"></i>
            </span>
                <h3 class="card-label">
                    Admin New Admin
                </h3>
            </div>

        </div>
        <div class="card-body">
            <div>
                <form action="{{route('admin.user.store')}}" method="post">
                    @csrf
                    <div class="card-body">

                        <div class="form-group">
                            <label>Name<span class="text-danger">*</span></label>
                            <input type="name" name="name" class="form-control"  placeholder="Enter Nmae"/>
                        </div>
                        <div class="form-group">
                            <label>Email address <span class="text-danger">*</span></label>
                            <input type="email" name="email" class="form-control"  placeholder="Enter email"/>
                            <span class="form-text text-muted">We'll never share your email with anyone else.</span>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Password <span class="text-danger">*</span></label>
                            <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password"/>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputPassword1">Password Confirmation<span class="text-danger">*</span></label>
                            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password"/>
                        </div>





                    </div>


                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary mr-2">Save</button>
                        <a href="{{route('admin.users')}}" class="btn btn-secondary">Cancel</a>
                    </div>
                </form>

            </div>
        </div>

    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layout.app')
@section('content')
    @push('css')
    @endpush
    @push('js')
    @endpush
    <div class="card card-custom">
        <div class="card-header">
            <div class="card-title">
            <span class="card-icon">
                <i class="fa fa-user-plus text-primary"></i>
            </span>
                <h3 class="card-label">
                    Admin New Admin
                </h3>
            </div>

        </div>
        <div class="card-body">
            <div>
                <form action="{{route('admin.update.user',['admin'=>$admin])}}" method="post">
                    @csrf
                    <div class="card-body">

                        <div class="form-group">
                            <label>Name<span class="text-danger">*</span></label>
                            <input type="name" name="name" class="form-control"  placeholder="Enter Nmae" value="{{@$admin->name}}"/>
                        </div>
                        <div class="form-group">
                            <label>Email address <span class="text-danger">*</span></label>
                            <input type="email" name="email" class="form-control"  placeholder="Enter email" value="{{@$admin->email}}"/>
                            <span class="form-text text-muted" > We'll never share your email with anyone else.</span>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Password <span class="text-danger">*</span></label>
                            <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password"/>
                            <div class="fv-plugins-message-container"><div data-field="text_input" data-validator="notEmpty">Leave password empty if you don't change it.</div> </div>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputPassword1">Password Confirmation<span class="text-danger">*</span></label>
                            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password"/>
                        </div>





                    </div>


                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary mr-2">Save</button>
                        <a href="{{route('admin.users')}}" class="btn btn-secondary">Cancel</a>
                    </div>
                </form>

            </div>
        </div>

    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layout.app')
@section('content')
    @push('css')
    @endpush

    <div class="card card-custom">
        <div class="card-header">
            <div class="card-title">
            <span class="card-icon">
                <i class="fa fa-user-cog text-primary"></i>
            </span>
                <h3 class="card-label">
                    Admin Management
                </h3>
            </div>
            <div class="card-toolbar">
                <a href="{{route('admin.create.user')}}" class="btn btn-sm btn-light-primary font-weight-bold">
                    <i class="fa fa-plus"></i> ADD NEW ADMIN
                </a>
            </div>
        </div>
        <div class="card-body">
            @if(session()->has('success'))

                <div class="alert alert-dismissible bg-success d-flex flex-column flex-sm-row p-5 mb-10">
                    <span class="svg-icon-2hx svg-icon-light me-4 mb-5 mb-sm-0"></span>
                    <div class="d-flex flex-column text-light pe-0 pr-sm-10">
                        <span>{{session()->get('success')}}</span>
                    </div>
                    <button type="button" class="position-absolute position-sm-relative m-2 m-sm-0 top-0 end-0 btn btn-icon ms-sm-auto" data-bs-dismiss="alert">
                        <span class="svg-icon svg-icon-2x svg-icon-light"></span>
                    </button>
                </div>
            @endif
            <div>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <td>#</td>
                        <td>Name</td>
                        <td>Email</td>
                        <td>Create At </td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $key=>$user)
                        <tr>
                            <td>{{ $key+ $users->firstItem() }}</td>
                            <td>{{$user->name}}</td>
                            <td>{{$user->email}}</td>
                            <td>{{$user->created_at}}</td>
                            <td>
                            <a href="{{route('admin.edit.user',['admin'=>$user])}}" class="btn btn-icon">
                                <i class="fa fa-user-edit"></i>
                            </a>

                                <form action="{{route('admin.user.destroy',['admin'=>$user->id])}}" method="post">

                                    @csrf
                                    <button type="submit" class="btn btn-icon red show_confirm">
                                        <i class="fa fa-trash"></i>
                                    </button>




                                </form>


                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="row text-center">
                    {{$users->links()}}
                </div>
            </div>
        </div>

    </div>
@endsection
{{--@push('js')--}}
{{--    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>--}}
{{--    <script type="text/javascript">--}}

{{--        $('.show_confirm').click (function(event) {--}}

{{--            var form = $(this).closest("form");--}}
{{--            var name = $(this).data ("name");--}}

{{--            event.preventDefault();--}}
{{--            swal ({--}}

{{--                title: "Are you sure you want to delete"+name+ '?',--}}
{{--                text: "If you delete this, it will be gone forever.",--}}
{{--                icon: "warning",--}}
{{--                buttons: true,--}}
{{--                dangerMode: true,--}}

{{--            })--}}

{{--                .then((willDelete) => {--}}

{{--                    if (willDelete) {--}}
{{--                        form.submit();--}}

{{--                    }--}}



{{--                });--}}

{{--        });--}}

{{--    </script>--}}
{{--@endpush--}}