routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[\App\Http\Controllers\websiteController::class,'news'])->name('news');
Route::get('/new-by-cat/{cat}',[\App\Http\Controllers\websiteController::class,'newsByCategory'])->name('get_news_by_cat');
Route::get('/test',[\App\Http\Controllers\Admin\Homecotroller::class,'welcome']);
Route::get('/about',[\App\Http\Controllers\websiteController::class,'about'])->name('website.about');


Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>'auth'],function (){
    Route::group(['prefix'=>'manage'],function(){
        Route::get('/',[\App\Http\Controllers\Admin\AdminController::class,'index'])->name('users');
        Route::get('/create',[\App\Http\Controllers\Admin\AdminController::class,'create'])->name('create.user');
        Route::get('/edit/{admin}',[\App\Http\Controllers\Admin\AdminController::class,'edit'])->name('edit.user');
        Route::post('/update/{admin}',[\App\Http\Controllers\Admin\AdminController::class,'update'])->name('update.user');
        Route::post('/store',[\App\Http\Controllers\Admin\AdminController::class,'store'])->name('user.store');
        Route::post('/destroy/{admin}',[\App\Http\Controllers\Admin\AdminController::class,'destroy'])->name('user.destroy');
    });
    Route::group(['prefix'=>'category'],function(){
        Route::get('/',[\App\Http\Controllers\Admin\CategoryController::class,'index'])->name('category');
        Route::get('/create',[\App\Http\Controllers\Admin\CategoryController::class,'create'])->name('category.create');
        Route::post('/store',[\App\Http\Controllers\Admin\CategoryController::class,'store'])->name('category.store');
        Route::get('/edit/{category}',[\App\Http\Controllers\Admin\CategoryController::class,'edit'])->name('category.edit');
        Route::post('/update/{category}',[\App\Http\Controllers\Admin\CategoryController::class,'update'])->name('category.update');
        Route::post('/destroy/{category}',[\App\Http\Controllers\Admin\categoryController::class,'destroy'])->name('category.destroy');

    });
    Route::group(['prefix'=>'news'],function (){
        Route::get('/',[\App\Http\Controllers\Admin\NewsController::class,'index'])->name('news');

        Route::get('/create',[\App\Http\Controllers\Admin\NewsController::class,'create'])->name('news.create');
        Route::post('/store',[\App\Http\Controllers\Admin\NewsController::class,'store'])->name('news.store');
        Route::get('/edit/{news}',[\App\Http\Controllers\Admin\NewsController::class,'edit'])->name('news.edit');
        Route::post('/update/{news}',[\App\Http\Controllers\Admin\NewsController::class,'update'])->name('news.update');
        Route::post('/destroy/{news}',[\App\Http\Controllers\Admin\NewsController::class,'destroy'])->name('news.destroy');
    });
    Route::get('/home',[\App\Http\Controllers\Admin\Homecotroller::class,'admin'])->name('admin');
});

Auth::routes(['register'=>false]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('admin');

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    use HasFactory;
    protected $fillable = [
        'newsAddress',
        'newsDetails',
        'main_image',
        'cat_id',
    ];
    protected $appends=['image_url'];

    public function getImageUrlAttribute()
    {
        if($this->main_image){
            return asset('imgs/'.$this->main_image);
        }
        return null;
    }

   public function category(){
        return $this->belongsTo(Category::class,'cat_id');
   }
}

app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\News;
use Illuminate\Http\Request;
use File;
class NewsController extends Controller
{
    public function index(){
        $news=News::get();
        $data=[
            'news'=>$news
        ];
        return view('admin.news.index',$data);
    }

    public function create(Request $request){

            $categories=Category::get();
            $data=['categories'=>$categories];
        return view('admin.news.add-news',$data);

    }
    public function store(Request $request){

//        $request->validate([
//
//            'image_file'=>'nullable|image'
//        ]);

        $imageName=null;

        if($request->hasFile('image_file')){

            $imageName = rand(0,9999).time().'.'.$request->image_file->extension();
            $path=public_path('imgs');
            if(!File::exists($path)) {
                File::makeDirectory($path, 0777, true, true);
                // path does not exist
            }
            $request->image_file->move($path, $imageName);
        }

        News::create([
            'newsAddress'=>$request->newsAddress,
            'newsDetails'=>$request->newsDetails,
            'main_image'=>$imageName,
            'cat_id'=>(int)$request->cat_id,
        ]);

//        $news = new News();
//        $news->newsAddress=$request->newsAddress;
//        $news->newsDetails=$request->newsDetails;
//        $news->save();
        return redirect()->to(route('admin.news'))->with('success','تم إضافة الخبر بنجاح');
    }
    public function edit(Request $request,News $news){
        $categories=Category::get();

        return view('admin.news.editNews',compact('news','categories'));

    }
    public function update(Request $request,News $news){
//        $request->validate([
//            'newsAddress'=>'required',
//            'newsDetails'=>'required',
////            'cat_id'=>'required',
//        ]);
        $news->newsAddress=$request->newsAddress;
        $news->newsDetails=$request->newsDetails;
        $news->cat_id=$request->cat_id;
        $main_image=$news->main_image;

        if($request->hasFile('image_file')){

            $imageName = rand(0,9999).time().'.'.$request->image_file->extension();
            $path=public_path('imgs');
            if(!File::exists($path)) {
                File::makeDirectory($path, 0777, true, true);
                // path does not exist
            }
            $request->image_file->move($path, $imageName);
            $news->main_image=$imageName;
        }
        $news->save();
//        if($request->hasFile('image_file')){
////            unlink(asset('ímgs/'.$main_image));
//        }
        return redirect()->to(route('admin.news'))->with('success','تم تحديث الخبر بنجاح');
    }
    public function destroy(Request $request,$news){
        $news=News::find($news);
        if ($news){
            $news->delete();
        }
        return redirect()->to(route('admin.news'))->with('success','تم حذف الخبر بنجاح');

    }
}

resources/views/admin/news/add-news.blade.php
@extends('admin.layout.app')
@section('content')
    @push('css')
    @endpush
    @push('js')
    @endpush
    <div class="card card-custom">
        <div class="card-header">
            <h3 class="card-title">
                Add News
            </h3>
        </div>
        <!--begin::Form-->
        <form class="form" action="{{route('admin.news.store')}}" method="post" enctype='multipart/form-data'>
            @csrf
            <div class="card-body">
                <div class="form-group">
                    <label class="">صورة الخبر</label>
                    <input type="file" name="image_file" accept="image/jpg,image/png,image/jpeg,image/svg"/>

                </div>

                <div class="form-group">
                    <label class=""> تصنيف الخبر</label>
                    <select name="cat_id" class="form-control">
                        @foreach($categories as $cat)
                        <option value="{{$cat->id}}">{{$cat->name}}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label>News Address</label>
                    <input type="text" name="newsAddress" class="form-control form-control-lg"  placeholder="News Address"/>
                    <label>News Details</label>
                    <textarea type="text" name="newsDetails" class="form-control form-control-lg"  placeholder="News Details"/></textarea>
                </div>


                <div class="card-footer">
                    <button type="submit" class="btn btn-success mr-2">Save</button>
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                </div>
            </div>
        </form>
        <!--end::Form-->
    </div
    >@endsection

resources/views/admin/news/editNews.blade.php
@extends('admin.layout.app')
@section('content')
    @push('css')
    @endpush
    @push('js')
    @endpush
    <div class="card card-custom">
        <div class="card-header">
            <h3 class="card-title">
                Add News
            </h3>
        </div>
        <!--begin::Form-->
        <form class="form" action="{{route('admin.news.update',['news'=>$news])}}" method="post"  enctype='multipart/form-data'>
            @csrf
            <div class="card-body">
                <div class="form-group">
                    <div class="text-center">
                        <img width="100" src="{{$news->image_url}}"/>
                    </div>

                    <label class="">صورة الخبر</label>
                    <input type="file" name="image_file" accept="image/jpg,image/png,image/jpeg,image/svg"/>

                </div>

                <div class="form-group">
                    <label class=""> تصنيف الخبر</label>
                    <select name="cat_id" class="form-control">
                        @foreach($categories as $cat)
                            <option value="{{$cat->id}}" {{$cat->id==$news->cat_id ? 'selected':''}}>{{$cat->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label>News Address</label>
                    <input type="text" name="newsAddress" class="form-control form-control-lg"  placeholder="News Address" value="{{@$news->newsAddress}}"/>
                    <label>News Details</label>
                    <textarea type="text" name="newsDetails" class="form-control form-control-lg"  placeholder="News Details" />{{@$news->newsDetails}}</textarea>



                </div>


                <div class="card-footer">
                    <button type="submit" class="btn btn-success mr-2">Save</button>
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                </div>
            </div>
        </form>
        <!--end::Form-->
    </div
    >@endsection

resources/views/admin/news/index.blade.php
@extends('admin.layout.app')
@section('content')
    @push('css')
    @endpush
    <div class="card card-custom">
        <div class="card-header">
            <div class="card-title">
            <span class="card-icon">
                <i class="fa fa-list-alt text-primary"></i>
            </span>
                <h3 class="card-label">
                    News Management
                </h3>
            </div>
            <div class="card-toolbar">
                <a href="{{route('admin.news.create')}}" class="btn btn-sm btn-light-primary font-weight-bold">
                    <i class="fa fa-plus"></i> ADD NEW NEWS
                </a>
            </div>
        </div>
        <div class="card-body">
            @if(session()->has('success'))

                <div class="alert alert-dismissible bg-success d-flex flex-column flex-sm-row p-5 mb-10">
                    <span class="svg-icon-2hx svg-icon-light me-4 mb-5 mb-sm-0"></span>
                    <div class="d-flex flex-column text-light pe-0 pr-sm-10">
                        <span>{{session()->get('success')}}</span>
                    </div>
                    <button type="button" class="position-absolute position-sm-relative m-2 m-sm-0 top-0 end-0 btn btn-icon ms-sm-auto" data-bs-dismiss="alert">
                        <span class="svg-icon svg-icon-2x svg-icon-light"></span>
                    </button>
                </div>
            @endif
            <div>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <td>#</td>
                        <td> صورة الخبر</td>
                        <td>تصنيف الخبر </td>
                        <td>Details News</td>
                        <td>Details News</td>

                    </tr>
                    </thead>
                    <tbody>
                    @foreach($news as $key=>$newss)
                        <tr>
                            <td>{{ $key+1}}</td>
                            <td><img src="{{$newss->image_url}}" width="70"/> </td>
                            <td>{{@$newss->category->name}}</td>
                            <td>{{$newss->newsAddress}}</td>
                            <td>{{$newss->newsDetails}}</td>
                            <td>
                                <a href="{{route('admin.news.edit',['news'=>$newss])}}" class="btn btn-icon">
                                    <i class="fa fa-user-edit"></i>
                                </a>





                                <form action="{{route('admin.news.destroy',['news'=>$newss->id])}}" method="post">

                                    @csrf
                                    <button type="submit" class="btn btn-icon red">
                                        <i class="fa fa-trash"></i>
                                    </button>




                                </form>


                            <td/>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="row text-center">
                    {{--                    {{$category->links()}}--}}
                </div>
            </div>
        </div>

    </div>
@endsection
{{--@push('js')--}}
{{--    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>--}}
{{--    <script type="text/javascript">--}}

{{--        $('.show_confirm').click (function(event) {--}}

{{--            var form = $(this).closest("form");--}}
{{--            var name = $(this).data ("name");--}}

{{--            event.preventDefault();--}}
{{--            swal ({--}}

{{--                title: "Are you sure you want to delete"+name+ '?',--}}
{{--                text: "If you delete this, it will be gone forever.",--}}
{{--                icon: "warning",--}}
{{--                buttons: true,--}}
{{--                dangerMode: true,--}}

{{--            })--}}

{{--                .then((willDelete) => {--}}

{{--                    if (willDelete) {--}}
{{--                        form.submit();--}}

{{--                    }--}}



{{--                });--}}

{{--        });--}}

{{--    </script>--}}
{{--@endpush--}}